name: Build and Push Trilink API

on:
  push:
    branches: [ "main" ]
    paths:
      - 'trilink-api/**'
      - '.github/workflows/build-trilink-api.yml'
  workflow_dispatch:

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build . --file Dockerfile --tag rinoruname/trilink-api:${{ env.IMAGE_TAG }}
        working-directory: trilink-api

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_PAT }}

      - name: Publish image
        run: |
          docker tag rinoruname/trilink-api:${{ env.IMAGE_TAG }} rinoruname/trilink-api:latest
          docker push rinoruname/trilink-api:${{ env.IMAGE_TAG }}
          docker push rinoruname/trilink-api:latest 