name: Build Trilink Web

on:
  push:
    branches: [ "main" ]
    paths:
      - 'trilink-web/**'
      - '.github/workflows/build-trilink-web.yml'
  workflow_dispatch:

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Build static assets
      working-directory: trilink-web
      env:
        ENV: local
      run: |
        npm install
        npm run build
        
    - name: build-image
      run: docker build . --file Dockerfile --build-arg ENV=local --tag rinoruname/trilink-web:${{ env.IMAGE_TAG }}
      working-directory: trilink-web

    - name: docker-login
      run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_PAT }}

    - name: publish-image
      run: |
        docker tag rinoruname/trilink-web:${{ env.IMAGE_TAG }} rinoruname/trilink-web:latest
        docker push rinoruname/trilink-web:${{ env.IMAGE_TAG }}
        docker push rinoruname/trilink-web:latest 