name: Build Trilink Web

on:
  push:
    branches: [ "main" ]
    paths:
      - 'trilink-web/**'
      - '.github/workflows/build-trilink-web.yml'
  workflow_dispatch:

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: build-image
        run: docker build . --file Dockerfile --tag rinoruname/trilink-web:${{ env.IMAGE_TAG }}
        working-directory: trilink-web

      - name: docker-login
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_PAT }}

      - name: publish-image
        run: |
          docker tag rinoruname/trilink-web:${{ env.IMAGE_TAG }} rinoruname/trilink-web:latest
          docker push rinoruname/trilink-web:${{ env.IMAGE_TAG }}
          docker push rinoruname/trilink-web:latest 