name: Validate Trilink Web

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'trilink-web/**'
      - '.github/workflows/validate-trilink-web-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: build-image
      run: docker build . --file Dockerfile --tag rinoruname/trilink-web:latest
      working-directory: trilink-web

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: trilink-web/package-lock.json

      - name: Install dependencies
        working-directory: ./trilink-web
        run: npm ci

#comment
      - name: Start and test web
        run: |
          docker network create app-network || true
          docker run -d --name trilink-web --network app-network \
            -p 80:80 \
            -e NEXT_PUBLIC_API_URL=http://localhost:4000 \
            -e API_URL=http://trilink-api:4000 \
            -e ENV=local \
            rinoruname/trilink-web:latest

          echo "Waiting for Web to start..."
          timeout 60s bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:80)" != "200" ]]; do sleep 5; done' || false
          echo "Web is up and running!"

      - name: Check logs if failed
        if: failure()
        run: |
          echo "Web Logs:"
          docker logs trilink-web 


#comment
